// Login
export const LOGIN_TYPE = 'LOGIN_TYPE'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const LOGOUT_USER = 'LOGOUT_USER'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
// Forget Password
export const FORGET_TYPE = 'FORGET_TYPE'

export const ERROR_TYPE = 'ERROR_TYPE'


// Environment 

export const ENVIRONMENT_DATA   =   'ENVIRONMENT_DATA'
export const ENVIRONMENT_CREATE = 'ENVIRONMENT_CREATE'
export const ENVIRONMENT_PATCH_DATA = 'ENVIRONMENT_PATCH_DATA'
export const ENVIRONMENT_PUT_DATA = 'ENVIRONMENT_PUT_DATA'
export const ENVIRONMENT_DELETE_DATA = 'ENVIRONMENT_DELETE_DATA'


// Channels

export const CHANNEL_LIST = 'CHANNEL_LIST'
export const CHANNEL_POST = 'CHANNEL_POST'
export const CHANNEL_PUT  = 'CHANNEL_PUT'
export const CHANNEL_PATCH = 'CHANNEL_PATCH'
export const CHANNEL_DELETE = "CHANNEL_DELETE"
export const CHANNEL_LIST_STATUS = 'CHANNEL_LIST_STATUS'


// Scenarios

export const SCENARIO_LIST = 'SCENARIO_LIST'
export const SCENARIO_POST = 'SCENARIO_POST'
export const SCENARIO_PUT  = 'SCENARIO_PUT'
export const SCENARIO_PATCH = 'SCENARIO_PATCH'
export const SCENARIO_DELETE = "SCENARIO_DELETE"
export const SCENARIO_EXEC = "SCENARIO_EXEC"


//Channels API
export const CHANNELAPI_POST='CHANNELAPI_POST'

//User Management
export const USER_MANAGEMENT_GET= 'USER_MANAGEMENT_GET'
export const USER_MANAGEMENT_POST = 'USER_MANAGEMENT_POST'
export const USER_MANAGEMENT_UPDATE = 'USER_MANAGEMENT_UPDTAE'
export const USER_MANAGEMENT_DELETE = 'USER_MANAGEMENT_DELETE'

export const CLEAR_DATA = 'CLEAR_DATA'

export const EXE_RESULT = 'EXE_RESULT'

export const VERIFY_TOKEN = 'VERIFY_TOKEN'

export const GET_CHANNEL_DATA = 'GET_CHANNEL_DATA'
